top_builddir=../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(PYTHON_CFLAGS)

OBJS = \
 core.o \
 dialogs.o \
 document.o \
 hooks.o \
 keybinding.o \
 load.o \
 menu.o \
 open.o \
 python.o

include $(top_srcdir)/Makefile.lib
