path_to_top=../..
include $(path_to_top)/Makefile.config

OBJS-$(CONFIG_EXMODE) += exmode.o

OBJS = document.o download.o edit.o info.o menu.o options.o progress.o status.o

include $(path_to_top)/Makefile.lib
