top_builddir=../../..
include $(top_builddir)/Makefile.config
INCLUDES += $(MUJS_CFLAGS)

OBJS = attr.obj attributes.obj collection.obj console.obj document.obj element.obj form.obj \
	forms.obj history.obj implementation.obj input.obj location.obj \
	localstorage.obj navigator.obj nodelist.obj screen.obj unibar.obj window.obj

include $(top_srcdir)/Makefile.lib
