path_to_top=../../..
include $(path_to_top)/Makefile.config

OBJS = apply.o css.o parser.o property.o scanner.o stylesheet.o value.o

# Do not forget to also add the .o to ../Makefile. Yes, it sucks.
all-l: $(OBJS)

include $(path_to_top)/Makefile.lib
