top_builddir=../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(LIBDOM_CFLAGS)
OBJS = apply.o css.o parser.o property.o scanner.o stylesheet.o value.o

include $(top_srcdir)/Makefile.lib
