top_builddir=../../../..
include $(top_builddir)/Makefile.config

OBJS = attr.o attributes.o collection.o console.o heartbeat.o history.o keyboard.o localstorage.o mapa.obj navigator.o screen.o

include $(top_srcdir)/Makefile.lib
