top_builddir=../../../..
include $(top_builddir)/Makefile.config

OBJS = attr.o attributes.o collection.o console.o forms.o heartbeat.o history.o input.o keyboard.o localstorage.o location.o mapa.obj message.o navigator.o nodelist.o screen.o unibar.o window.o xhr.o

include $(top_srcdir)/Makefile.lib
