top_builddir=../../../..
include $(top_builddir)/Makefile.config

OBJS = attr.o attributes.o collection.o console.o heartbeat.o history.o keyboard.o localstorage.o mapa.obj message.o navigator.o nodelist.o screen.o unibar.o

include $(top_srcdir)/Makefile.lib
