#
# [ win64 ] elinks docker development environment 
#

FROM debian:latest

RUN apt-get update; apt-get -y install rsync vim screen git make automake gcc-mingw-w64-x86-64 bash g++-mingw-w64-x86-64 libssl-dev
RUN cd /root; git clone https://github.com/rkd77/elinks

