#ifndef EL__DOCUMENT_DOM_ECMASCRIPT_SPIDERMONKEY_HTML_HTMLTABLECAPTIONELEMENT_H
#define EL__DOCUMENT_DOM_ECMASCRIPT_SPIDERMONKEY_HTML_HTMLTABLECAPTIONELEMENT_H

#include "ecmascript/spidermonkey/util.h"

extern const JSClass HTMLTableCaptionElement_class;
extern const JSFunctionSpec HTMLTableCaptionElement_funcs[];
extern const JSPropertySpec HTMLTableCaptionElement_props[];

#endif
