#ifndef EL__DOCUMENT_DOM_ECMASCRIPT_SPIDERMONKEY_HTML_HTMLTABLESECTIONELEMENT_H
#define EL__DOCUMENT_DOM_ECMASCRIPT_SPIDERMONKEY_HTML_HTMLTABLESECTIONELEMENT_H

#include "ecmascript/spidermonkey/util.h"

extern const JSClass HTMLTableSectionElement_class;
extern const JSFunctionSpec HTMLTableSectionElement_funcs[];
extern const JSPropertySpec HTMLTableSectionElement_props[];

#endif
