top_builddir=../../../../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(SPIDERMONKEY_CFLAGS)
OBJS = HTMLAnchorElement.o HTMLAppletElement.o HTMLAreaElement.o \
HTMLBaseElement.o HTMLBaseFontElement.o HTMLBodyElement.o \
HTMLBRElement.o HTMLButtonElement.o HTMLCollection.o \
HTMLDirectoryElement.o HTMLDivElement.o HTMLDListElement.o \
HTMLDocument.o HTMLElement.o HTMLFieldSetElement.o \
HTMLFontElement.o HTMLFormElement.o HTMLFrameElement.o \
HTMLFrameSetElement.o HTMLHeadElement.o HTMLHeadingElement.o \
HTMLHRElement.o HTMLHtmlElement.o HTMLIFrameElement.o \
HTMLImageElement.o HTMLInputElement.o HTMLIsIndexElement.o \
HTMLLabelElement.o HTMLLegendElement.o HTMLLIElement.o \
HTMLLinkElement.o HTMLMapElement.o HTMLMenuElement.o \
HTMLMetaElement.o HTMLModElement.o HTMLObjectElement.o \
HTMLOListElement.o HTMLOptGroupElement.o HTMLOptionElement.o \
HTMLOptionsCollection.o HTMLParagraphElement.o HTMLParamElement.o \
HTMLPreElement.o HTMLQuoteElement.o HTMLScriptElement.o \
HTMLSelectElement.o HTMLStyleElement.o HTMLTableCaptionElement.o \
HTMLTableCellElement.o HTMLTableColElement.o HTMLTableElement.o \
HTMLTableRowElement.o HTMLTableSectionElement.o HTMLTextAreaElement.o \
HTMLTitleElement.o HTMLUListElement.o

include $(top_srcdir)/Makefile.lib
