top_builddir=../../..
include $(top_builddir)/Makefile.config
INCLUDES += $(SEE_CFLAGS)

OBJS = checktype.o document.o form.o input.o location.o navigator.o strings.o unibar.o window.o

include $(top_srcdir)/Makefile.lib
