top_builddir=../../..
include $(top_builddir)/Makefile.config

OBJS = attr.o attributes.o collection.o console.o document.o element.o form.o \
	forms.o heartbeat.o history.o implementation.o input.o location.o \
	localstorage.o navigator.o nodelist.o screen.o unibar.o window.o

include $(top_srcdir)/Makefile.lib
