top_builddir=../../../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(SPIDERMONKEY_CFLAGS)
OBJS = Attr.o CDATASection.o CharacterData.o Comment.o Document.o \
DocumentFragment.o DocumentType.o DOMConfiguration.o \
DOMError.o DOMErrorHandler.o DOMException.o \
DOMImplementation.o DOMImplementationList.o \
DOMImplementationRegistry.o DOMImplementationSource.o \
DOMLocator.o DOMStringList.o Element.o Entity.o \
EntityReference.o NamedNodeMap.o NameList.o \
Node.o NodeList.o Notation.o ProcessingInstruction.o \
Text.o TypeInfo.o UserDataHandler.o

include $(top_srcdir)/Makefile.lib
