path_to_top=../..
include $(path_to_top)/Makefile.config

SUBDIRS-$(CONFIG_CSS)	+= css
SUBDIRS-$(CONFIG_DOM)	+= dom sgml

SUBDIRS = html plain

OBJS = docdata.o document.o forms.o options.o refresh.o renderer.o

include $(path_to_top)/Makefile.lib
