top_builddir=../../..
include $(top_builddir)/Makefile.config

OBJS-$(CONFIG_CGI) += cgi.o
OBJS-$(CONFIG_DGI) += dgi.o

OBJS = file.o

OBJS-$(CONFIG_MAILCAP) += mailcap.o

include $(top_srcdir)/Makefile.lib
