top_builddir=../../..
include $(top_builddir)/Makefile.config
INCLUDES += $(SPIDERMONKEY_CFLAGS)

OBJS = localstorage.obj navigator.obj screen.obj unibar.obj window.obj xhr.obj

include $(top_srcdir)/Makefile.lib
