top_builddir=../../..
include $(top_builddir)/Makefile.config
INCLUDES += $(SPIDERMONKEY_CFLAGS)

OBJS = attr.o attributes.o collection.o console.o document.o element.o form.o heartbeat.o history.o implementation.o \
	location.o localstorage.o localstorage-db.o navigator.o nodelist.o screen.o unibar.o window.o

include $(top_srcdir)/Makefile.lib
