'\" t
.\"     Title: elinkskeys
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 10/26/2012
.\"    Manual: ELinks keybindings
.\"    Source: ELinks 0.12pre6
.\"  Language: English
.\"
.TH "ELINKSKEYS" "5" "10/26/2012" "ELinks 0\&.12pre6" "ELinks keybindings"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
elinkskeys \- keybindings for ELinks
.SH "SYNOPSIS"
.sp
Information on how to configure keybinding and overview of the default keybindings\&.
.SH "DESCRIPTION"
.sp
Key binding for elinks should be placed in the file ~/\&.elinks/elinks\&.conf\&. Note that any information regarding their format/structure may not be up\-to\-date\&. If you will discover that, please feed us with a patch\&.
.sp
Key binding statements are of the form:
.sp
.if n \{\
.RS 4
.\}
.nf
bind <keymap> <keystroke> = <action>
.fi
.if n \{\
.RE
.\}
.sp
where:
.PP
<keymap>
.RS 4
is
\fImain\fR,
\fIedit\fR, or
\fImenu\fR\&. The main keymap is used for general browsing\&. The edit keymap is used for editing text fields\&. The menu keymap is used for navigating menus\&.
.RE
.PP
<keystroke>
.RS 4
is a case sensitive key, which you can prefix with
\fICtrl\-\fR,
\fIAlt\-\fR, or both\&.
\fICtrl\-\fR
must be followed by an uppercase key\&. See below for a list of valid keys\&.
.RE
.PP
<action>
.RS 4
is what the key should do\&. The actions available are dependent on the keymap, and are listed separately below\&.
.RE
.sp
All words/strings may all be quoted "like so"\&. Backslashes are escape characters, even if not between quotes\&. Lines beginning with a hash character (#) are comments\&.
.sp
Keys can be unbound just by binding them to the special \fInone\fR action\&. It may be of use if you accidentally type a key often\&.
.SH "EXAMPLE BINDINGS"
.sp
Some sample keybindings:
.sp
.if n \{\
.RS 4
.\}
.nf
bind "main" "v" = "view\-image"
bind "main" "l" = "jump\-to\-link"
bind "main" "L" = "link\-menu"
bind "main" "F10" = "file\-menu"
bind "main" "F9" = "menu"
bind "main" "Escape" = "menu"
bind "edit" "Ctrl\-R" = "auto\-complete\-unambiguous"
bind "edit" "Ctrl\-W" = "auto\-complete"
bind "edit" "Ctrl\-K" = "kill\-to\-eol"
bind "menu" "Ctrl\-B" = "page\-up"
bind "menu" "PageUp" = "page\-up"
bind "menu" "Ctrl\-F" = "page\-down"
bind "menu" "PageDown" = "page\-down"
# ELinks with Lua support
bind "main" "," = "lua\-console"
.fi
.if n \{\
.RE
.\}
.SH "KEYS"
.sp
Valid keys are: alphanumeric characters, punctuation, \fIEnter\fR, \fIBackspace\fR, \fITab\fR, \fIEscape\fR, \fILeft\fR, \fIRight\fR, \fIUp\fR, \fIDown\fR, \fIInsert\fR, \fIDelete\fR, \fIHome\fR, \fIEnd\fR, \fIPageUp\fR, \fIPageDown\fR, \fIF1\fR to \fIF12\fR\&.
.sp
Some keys will need to be quoted or escaped\&. For example, space can be written as " " (quote space quote), and the quote itself as \e" (backslash quote)\&. Backslash can be written as \e\e (double backslash)\&.
.SH "KEYMAP ACTIONS"
.SS "MAIN ACTIONS"
.PP
abort\-connection
.RS 4
Abort connection\&.
.RE
.PP
add\-bookmark
.RS 4
Add a new bookmark\&.
.RE
.PP
add\-bookmark\-link
.RS 4
Add a new bookmark using current link\&.
.RE
.PP
add\-bookmark\-tabs
.RS 4
Bookmark all open tabs\&.
.RE
.PP
auth\-manager
.RS 4
Open authentication manager\&.
.RE
.PP
backspace\-prefix
.RS 4
Backspace the last entered digit of the current prefix\&.
.RE
.PP
bookmark\-manager
.RS 4
Open bookmark manager\&.
.RE
.PP
cache\-manager
.RS 4
Open cache manager\&.
.RE
.PP
cache\-minimize
.RS 4
Free unused cache entries\&.
.RE
.PP
cookie\-manager
.RS 4
Open cookie manager\&.
.RE
.PP
cookies\-load
.RS 4
Reload cookies file\&.
.RE
.PP
copy\-clipboard
.RS 4
Copy text to clipboard\&.
.RE
.PP
document\-info
.RS 4
Show information about the current page\&.
.RE
.PP
download\-manager
.RS 4
Open download manager\&.
.RE
.PP
exmode
.RS 4
Enter ex\-mode (command line)\&.
.RE
.PP
file\-menu
.RS 4
Open the File menu\&.
.RE
.PP
find\-next
.RS 4
Find the next occurrence of the current search text\&.
.RE
.PP
find\-next\-back
.RS 4
Find the previous occurrence of the current search text\&.
.RE
.PP
forget\-credentials
.RS 4
Forget authentication credentials\&.
.RE
.PP
formhist\-manager
.RS 4
Open form history manager\&.
.RE
.PP
frame\-external\-command
.RS 4
Pass URI of current frame to external command\&.
.RE
.PP
frame\-maximize
.RS 4
Maximize the current frame\&.
.RE
.PP
frame\-next
.RS 4
Move to the next frame\&.
.RE
.PP
frame\-prev
.RS 4
Move to the previous frame\&.
.RE
.PP
goto\-url
.RS 4
Open "Go to URL" dialog box\&.
.RE
.PP
goto\-url\-current
.RS 4
Open "Go to URL" dialog box containing the current URL\&.
.RE
.PP
goto\-url\-current\-link
.RS 4
Open "Go to URL" dialog box containing the current link URL\&.
.RE
.PP
goto\-url\-home
.RS 4
Go to the homepage\&.
.RE
.PP
header\-info
.RS 4
Show information about the current page protocol headers\&.
.RE
.PP
history\-manager
.RS 4
Open history manager\&.
.RE
.PP
history\-move\-back
.RS 4
Return to the previous document in history\&.
.RE
.PP
history\-move\-forward
.RS 4
Go forward in history\&.
.RE
.PP
jump\-to\-link
.RS 4
Jump to link\&.
.RE
.PP
keybinding\-manager
.RS 4
Open keybinding manager\&.
.RE
.PP
kill\-backgrounded\-connections
.RS 4
Kill all backgrounded connections\&.
.RE
.PP
link\-download
.RS 4
Download the current link\&.
.RE
.PP
link\-download\-image
.RS 4
Download the current image\&.
.RE
.PP
link\-download\-resume
.RS 4
Attempt to resume download of the current link\&.
.RE
.PP
link\-external\-command
.RS 4
Pass URI of current link to external command\&.
.RE
.PP
link\-follow
.RS 4
Follow the current link\&.
.RE
.PP
link\-follow\-reload
.RS 4
Follow the current link, forcing reload of the target\&.
.RE
.PP
link\-menu
.RS 4
Open the link context menu\&.
.RE
.PP
link\-form\-menu
.RS 4
Open the form fields menu\&.
.RE
.PP
lua\-console
.RS 4
Open a Lua console\&.
.RE
.PP
mark\-goto
.RS 4
Go at a specified mark\&.
.RE
.PP
mark\-set
.RS 4
Set a mark\&.
.RE
.PP
menu
.RS 4
Activate the menu\&.
.RE
.PP
move\-cursor\-down
.RS 4
Move cursor down\&.
.RE
.PP
move\-cursor\-left
.RS 4
Move cursor left\&.
.RE
.PP
move\-cursor\-line\-start
.RS 4
Move cursor to the start of the line\&.
.RE
.PP
move\-cursor\-right
.RS 4
Move cursor right\&.
.RE
.PP
move\-cursor\-up
.RS 4
Move cursor up\&.
.RE
.PP
move\-document\-end
.RS 4
Move to the end of the document\&.
.RE
.PP
move\-document\-start
.RS 4
Move to the start of the document\&.
.RE
.PP
move\-link\-down
.RS 4
Move one link down\&.
.RE
.PP
move\-link\-down\-line
.RS 4
Move to the next line with a link\&.
.RE
.PP
move\-link\-left
.RS 4
Move one link left\&.
.RE
.PP
move\-link\-left\-line
.RS 4
Move one link left or to the previous link\&.
.RE
.PP
move\-link\-next
.RS 4
Move to the next link\&.
.RE
.PP
move\-link\-prev
.RS 4
Move to the previous link\&.
.RE
.PP
move\-link\-right
.RS 4
Move one link right\&.
.RE
.PP
move\-link\-right\-line
.RS 4
Move one link right or to the next link\&.
.RE
.PP
move\-link\-up
.RS 4
Move one link up\&.
.RE
.PP
move\-link\-up\-line
.RS 4
Move to the previous line with a link\&.
.RE
.PP
move\-page\-down
.RS 4
Move downwards by a page\&.
.RE
.PP
move\-page\-up
.RS 4
Move upwards by a page\&.
.RE
.PP
open\-link\-in\-new\-tab
.RS 4
Open the current link in a new tab\&.
.RE
.PP
open\-link\-in\-new\-tab\-in\-background
.RS 4
Open the current link in a new tab in the background\&.
.RE
.PP
open\-link\-in\-new\-window
.RS 4
Open the current link in a new window\&.
.RE
.PP
open\-new\-tab
.RS 4
Open a new tab\&.
.RE
.PP
open\-new\-tab\-in\-background
.RS 4
Open a new tab in the background\&.
.RE
.PP
open\-new\-window
.RS 4
Open a new window\&.
.RE
.PP
open\-os\-shell
.RS 4
Open an OS shell\&.
.RE
.PP
options\-manager
.RS 4
Open options manager\&.
.RE
.PP
quit
.RS 4
Open a quit confirmation dialog box\&.
.RE
.PP
really\-quit
.RS 4
Quit without confirmation\&.
.RE
.PP
redraw
.RS 4
Redraw the terminal\&.
.RE
.PP
reload
.RS 4
Reload the current page\&.
.RE
.PP
rerender
.RS 4
Re\-render the current page\&.
.RE
.PP
reset\-form
.RS 4
Reset form items to their initial values\&.
.RE
.PP
resource\-info
.RS 4
Show information about the currently used resources\&.
.RE
.PP
save\-as
.RS 4
Save the current document in source form\&.
.RE
.PP
save\-formatted
.RS 4
Save the current document in formatted form\&.
.RE
.PP
save\-options
.RS 4
Save options\&.
.RE
.PP
save\-url\-as
.RS 4
Save URL as\&.
.RE
.PP
scroll\-down
.RS 4
Scroll down\&.
.RE
.PP
scroll\-left
.RS 4
Scroll left\&.
.RE
.PP
scroll\-right
.RS 4
Scroll right\&.
.RE
.PP
scroll\-up
.RS 4
Scroll up\&.
.RE
.PP
search
.RS 4
Search for a text pattern\&.
.RE
.PP
search\-back
.RS 4
Search backwards for a text pattern\&.
.RE
.PP
search\-typeahead
.RS 4
Search link text by typing ahead\&.
.RE
.PP
search\-typeahead\-link
.RS 4
Search link text by typing ahead\&.
.RE
.PP
search\-typeahead\-text
.RS 4
Search document text by typing ahead\&.
.RE
.PP
search\-typeahead\-text\-back
.RS 4
Search document text backwards by typing ahead\&.
.RE
.PP
show\-term\-options
.RS 4
Show terminal options dialog\&.
.RE
.PP
submit\-form
.RS 4
Submit form\&.
.RE
.PP
submit\-form\-reload
.RS 4
Submit form and reload\&.
.RE
.PP
tab\-close
.RS 4
Close tab\&.
.RE
.PP
tab\-close\-all\-but\-current
.RS 4
Close all tabs but the current one\&.
.RE
.PP
tab\-external\-command
.RS 4
Pass URI of current tab to external command\&.
.RE
.PP
tab\-menu
.RS 4
Open the tab menu\&.
.RE
.PP
tab\-move\-left
.RS 4
Move the current tab to the left\&.
.RE
.PP
tab\-move\-right
.RS 4
Move the current tab to the right\&.
.RE
.PP
tab\-next
.RS 4
Next tab\&.
.RE
.PP
tab\-prev
.RS 4
Previous tab\&.
.RE
.PP
terminal\-resize
.RS 4
Open the terminal resize dialog\&.
.RE
.PP
toggle\-css
.RS 4
Toggle rendering of page using CSS\&.
.RE
.PP
toggle\-display\-images
.RS 4
Toggle displaying of links to images\&.
.RE
.PP
toggle\-display\-tables
.RS 4
Toggle rendering of tables\&.
.RE
.PP
toggle\-document\-colors
.RS 4
Toggle usage of document specific colors\&.
.RE
.PP
toggle\-html\-plain
.RS 4
Toggle rendering page as HTML / plain text\&.
.RE
.PP
toggle\-mouse
.RS 4
Toggle mouse handling\&.
.RE
.PP
toggle\-numbered\-links
.RS 4
Toggle displaying of links numbers\&.
.RE
.PP
toggle\-plain\-compress\-empty\-lines
.RS 4
Toggle plain renderer compression of empty lines\&.
.RE
.PP
toggle\-wrap\-text
.RS 4
Toggle wrapping of text\&.
.RE
.PP
view\-image
.RS 4
View the current image\&.
.RE
.SS "EDIT ACTIONS"
.PP
auto\-complete
.RS 4
Attempt to auto\-complete the input\&.
.RE
.PP
auto\-complete\-file
.RS 4
Attempt to auto\-complete a local file\&.
.RE
.PP
auto\-complete\-unambiguous
.RS 4
Attempt to unambiguously auto\-complete the input\&.
.RE
.PP
backspace
.RS 4
Delete character in front of the cursor\&.
.RE
.PP
beginning\-of\-buffer
.RS 4
Go to the first line of the buffer\&.
.RE
.PP
cancel
.RS 4
Cancel current state\&.
.RE
.PP
copy\-clipboard
.RS 4
Copy text to clipboard\&.
.RE
.PP
cut\-clipboard
.RS 4
Cut text to clipboard\&.
.RE
.PP
delete
.RS 4
Delete character under cursor\&.
.RE
.PP
down
.RS 4
Move cursor downwards\&.
.RE
.PP
end
.RS 4
Go to the end of the page/line\&.
.RE
.PP
end\-of\-buffer
.RS 4
Go to the last line of the buffer\&.
.RE
.PP
enter
.RS 4
Follow the current link\&.
.RE
.PP
home
.RS 4
Go to the start of the page/line\&.
.RE
.PP
kill\-to\-bol
.RS 4
Delete to beginning of line\&.
.RE
.PP
kill\-to\-eol
.RS 4
Delete to end of line\&.
.RE
.PP
kill\-word\-back
.RS 4
Delete backwards to start of word\&.
.RE
.PP
left
.RS 4
Move the cursor left\&.
.RE
.PP
move\-backward\-word
.RS 4
Move cursor before current word\&.
.RE
.PP
move\-forward\-word
.RS 4
Move cursor after current word\&.
.RE
.PP
next\-item
.RS 4
Move to the next item\&.
.RE
.PP
open\-external
.RS 4
Open in external editor\&.
.RE
.PP
paste\-clipboard
.RS 4
Paste text from the clipboard\&.
.RE
.PP
previous\-item
.RS 4
Move to the previous item\&.
.RE
.PP
redraw
.RS 4
Redraw the terminal\&.
.RE
.PP
right
.RS 4
Move the cursor right\&.
.RE
.PP
search\-toggle\-regex
.RS 4
Toggle regex matching (type\-ahead searching)\&.
.RE
.PP
up
.RS 4
Move cursor upwards\&.
.RE
.SS "MENU ACTIONS"
.PP
cancel
.RS 4
Cancel current state\&.
.RE
.PP
delete
.RS 4
Delete character under cursor\&.
.RE
.PP
down
.RS 4
Move cursor downwards\&.
.RE
.PP
end
.RS 4
Go to the end of the page/line\&.
.RE
.PP
enter
.RS 4
Follow the current link\&.
.RE
.PP
expand
.RS 4
Expand item\&.
.RE
.PP
home
.RS 4
Go to the start of the page/line\&.
.RE
.PP
left
.RS 4
Move the cursor left\&.
.RE
.PP
mark\-item
.RS 4
Mark item\&.
.RE
.PP
next\-item
.RS 4
Move to the next item\&.
.RE
.PP
page\-down
.RS 4
Move downwards by a page\&.
.RE
.PP
page\-up
.RS 4
Move upwards by a page\&.
.RE
.PP
previous\-item
.RS 4
Move to the previous item\&.
.RE
.PP
redraw
.RS 4
Redraw the terminal\&.
.RE
.PP
right
.RS 4
Move the cursor right\&.
.RE
.PP
search
.RS 4
Search for a text pattern\&.
.RE
.PP
select
.RS 4
Select current highlighted item\&.
.RE
.PP
unexpand
.RS 4
Collapse item\&.
.RE
.PP
up
.RS 4
Move cursor upwards\&.
.RE
.SH "DEFAULT BINDINGS"
.sp
The default bindings are shown below\&. Any bindings in ~/\&.elinks/elinks\&.conf will override these\&.
.SS "MAIN KEYS"
.PP
\fISpace\fR
.RS 4
Move downwards by a page (\fImove\-page\-down\fR)
.RE
.PP
\fI"#"\fR
.RS 4
Search link text by typing ahead (\fIsearch\-typeahead\fR)
.RE
.PP
\fI"%"\fR
.RS 4
Toggle usage of document specific colors (\fItoggle\-document\-colors\fR)
.RE
.PP
\fI"*"\fR
.RS 4
Toggle displaying of links to images (\fItoggle\-display\-images\fR)
.RE
.PP
\fI","\fR
.RS 4
Open a Lua console (\fIlua\-console\fR)
.RE
.PP
\fI"\&."\fR
.RS 4
Toggle displaying of links numbers (\fItoggle\-numbered\-links\fR)
.RE
.PP
\fI"/"\fR
.RS 4
Search for a text pattern (\fIsearch\fR)
.RE
.PP
\fI":"\fR
.RS 4
Enter ex\-mode (command line) (\fIexmode\fR)
.RE
.PP
\fI"<"\fR
.RS 4
Previous tab (\fItab\-prev\fR)
.RE
.PP
\fIAlt\-"<"\fR
.RS 4
Move the current tab to the left (\fItab\-move\-left\fR)
.RE
.PP
\fI"="\fR
.RS 4
Show information about the current page (\fIdocument\-info\fR)
.RE
.PP
\fI">"\fR
.RS 4
Next tab (\fItab\-next\fR)
.RE
.PP
\fIAlt\-">"\fR
.RS 4
Move the current tab to the right (\fItab\-move\-right\fR)
.RE
.PP
\fI"?"\fR
.RS 4
Search backwards for a text pattern (\fIsearch\-back\fR)
.RE
.PP
\fI"A"\fR
.RS 4
Add a new bookmark using current link (\fIadd\-bookmark\-link\fR)
.RE
.PP
\fICtrl\-"A"\fR
.RS 4
Move to the start of the document (\fImove\-document\-start\fR)
.RE
.PP
\fICtrl\-"B"\fR
.RS 4
Move upwards by a page (\fImove\-page\-up\fR)
.RE
.PP
\fI"C"\fR
.RS 4
Open cache manager (\fIcache\-manager\fR)
.RE
.PP
\fI"D"\fR
.RS 4
Open download manager (\fIdownload\-manager\fR)
.RE
.PP
\fI"E"\fR
.RS 4
Open "Go to URL" dialog box containing the current link URL (\fIgoto\-url\-current\-link\fR)
.RE
.PP
\fICtrl\-"E"\fR
.RS 4
Move to the end of the document (\fImove\-document\-end\fR)
.RE
.PP
\fI"F"\fR
.RS 4
Open form history manager (\fIformhist\-manager\fR)
.RE
.PP
\fICtrl\-"F"\fR
.RS 4
Move downwards by a page (\fImove\-page\-down\fR)
.RE
.PP
\fI"G"\fR
.RS 4
Open "Go to URL" dialog box containing the current URL (\fIgoto\-url\-current\fR)
.RE
.PP
\fI"H"\fR
.RS 4
Go to the homepage (\fIgoto\-url\-home\fR)
.RE
.PP
\fI"K"\fR
.RS 4
Open cookie manager (\fIcookie\-manager\fR)
.RE
.PP
\fICtrl\-"K"\fR
.RS 4
Reload cookies file (\fIcookies\-load\fR)
.RE
.PP
\fI"L"\fR
.RS 4
Open the link context menu (\fIlink\-menu\fR)
.RE
.PP
\fICtrl\-"L"\fR
.RS 4
Redraw the terminal (\fIredraw\fR)
.RE
.PP
\fI"N"\fR
.RS 4
Find the previous occurrence of the current search text (\fIfind\-next\-back\fR)
.RE
.PP
\fICtrl\-"N"\fR
.RS 4
Scroll down (\fIscroll\-down\fR)
.RE
.PP
\fICtrl\-"P"\fR
.RS 4
Scroll up (\fIscroll\-up\fR)
.RE
.PP
\fI"Q"\fR
.RS 4
Quit without confirmation (\fIreally\-quit\fR)
.RE
.PP
\fICtrl\-"R"\fR
.RS 4
Reload the current page (\fIreload\fR)
.RE
.PP
\fI"T"\fR
.RS 4
Open the current link in a new tab in the background (\fIopen\-link\-in\-new\-tab\-in\-background\fR)
.RE
.PP
\fI"W"\fR
.RS 4
Toggle wrapping of text (\fItoggle\-wrap\-text\fR)
.RE
.PP
\fI"["\fR
.RS 4
Scroll left (\fIscroll\-left\fR)
.RE
.PP
\fI"\*(Aq"\fR
.RS 4
Go at a specified mark (\fImark\-goto\fR)
.RE
.PP
\fI"\e"\fR
.RS 4
Toggle rendering page as HTML / plain text (\fItoggle\-html\-plain\fR)
.RE
.PP
\fI"]"\fR
.RS 4
Scroll right (\fIscroll\-right\fR)
.RE
.PP
\fI"a"\fR
.RS 4
Add a new bookmark (\fIadd\-bookmark\fR)
.RE
.PP
\fI"b"\fR
.RS 4
Move upwards by a page (\fImove\-page\-up\fR)
.RE
.PP
\fI"c"\fR
.RS 4
Close tab (\fItab\-close\fR)
.RE
.PP
\fI"d"\fR
.RS 4
Download the current link (\fIlink\-download\fR)
.RE
.PP
\fI"e"\fR
.RS 4
Open the tab menu (\fItab\-menu\fR)
.RE
.PP
\fI"f"\fR
.RS 4
Maximize the current frame (\fIframe\-maximize\fR)
.RE
.PP
\fI"g"\fR
.RS 4
Open "Go to URL" dialog box (\fIgoto\-url\fR)
.RE
.PP
\fI"h"\fR
.RS 4
Open history manager (\fIhistory\-manager\fR)
.RE
.PP
\fI"k"\fR
.RS 4
Open keybinding manager (\fIkeybinding\-manager\fR)
.RE
.PP
\fI"l"\fR
.RS 4
Jump to link (\fIjump\-to\-link\fR)
.RE
.PP
\fI"m"\fR
.RS 4
Set a mark (\fImark\-set\fR)
.RE
.PP
\fI"n"\fR
.RS 4
Find the next occurrence of the current search text (\fIfind\-next\fR)
.RE
.PP
\fI"o"\fR
.RS 4
Open options manager (\fIoptions\-manager\fR)
.RE
.PP
\fI"q"\fR
.RS 4
Open a quit confirmation dialog box (\fIquit\fR)
.RE
.PP
\fI"r"\fR
.RS 4
Attempt to resume download of the current link (\fIlink\-download\-resume\fR)
.RE
.PP
\fI"s"\fR
.RS 4
Open bookmark manager (\fIbookmark\-manager\fR)
.RE
.PP
\fI"t"\fR
.RS 4
Open a new tab (\fIopen\-new\-tab\fR)
.RE
.PP
\fI"u"\fR
.RS 4
Go forward in history (\fIhistory\-move\-forward\fR)
.RE
.PP
\fI"v"\fR
.RS 4
View the current image (\fIview\-image\fR)
.RE
.PP
\fI"x"\fR
.RS 4
Follow the current link, forcing reload of the target (\fIlink\-follow\-reload\fR)
.RE
.PP
\fI"z"\fR
.RS 4
Abort connection (\fIabort\-connection\fR)
.RE
.PP
\fI"{"\fR
.RS 4
Scroll left (\fIscroll\-left\fR)
.RE
.PP
\fI"|"\fR
.RS 4
Show information about the current page protocol headers (\fIheader\-info\fR)
.RE
.PP
\fI"}"\fR
.RS 4
Scroll right (\fIscroll\-right\fR)
.RE
.PP
\fIBackspace\fR
.RS 4
Backspace the last entered digit of the current prefix (\fIbackspace\-prefix\fR)
.RE
.PP
\fIDelete\fR
.RS 4
Scroll down (\fIscroll\-down\fR)
.RE
.PP
\fIDown\fR
.RS 4
Move to the next link (\fImove\-link\-next\fR)
.RE
.PP
\fIEnd\fR
.RS 4
Move to the end of the document (\fImove\-document\-end\fR)
.RE
.PP
\fIEnter\fR
.RS 4
Follow the current link (\fIlink\-follow\fR)
.RE
.PP
\fICtrl\-Enter\fR
.RS 4
Follow the current link, forcing reload of the target (\fIlink\-follow\-reload\fR)
.RE
.PP
\fIEscape\fR
.RS 4
Activate the menu (\fImenu\fR)
.RE
.PP
\fIF10\fR
.RS 4
Open the File menu (\fIfile\-menu\fR)
.RE
.PP
\fIF9\fR
.RS 4
Activate the menu (\fImenu\fR)
.RE
.PP
\fIHome\fR
.RS 4
Move to the start of the document (\fImove\-document\-start\fR)
.RE
.PP
\fIInsert\fR
.RS 4
Scroll up (\fIscroll\-up\fR)
.RE
.PP
\fICtrl\-Insert\fR
.RS 4
Copy text to clipboard (\fIcopy\-clipboard\fR)
.RE
.PP
\fILeft\fR
.RS 4
Return to the previous document in history (\fIhistory\-move\-back\fR)
.RE
.PP
\fIPageDown\fR
.RS 4
Move downwards by a page (\fImove\-page\-down\fR)
.RE
.PP
\fIPageUp\fR
.RS 4
Move upwards by a page (\fImove\-page\-up\fR)
.RE
.PP
\fIRight\fR
.RS 4
Follow the current link (\fIlink\-follow\fR)
.RE
.PP
\fICtrl\-Right\fR
.RS 4
Follow the current link, forcing reload of the target (\fIlink\-follow\-reload\fR)
.RE
.PP
\fITab\fR
.RS 4
Move to the next frame (\fIframe\-next\fR)
.RE
.PP
\fIAlt\-Tab\fR
.RS 4
Move to the previous frame (\fIframe\-prev\fR)
.RE
.PP
\fIShift\-Tab\fR
.RS 4
Move to the previous frame (\fIframe\-prev\fR)
.RE
.PP
\fIUp\fR
.RS 4
Move to the previous link (\fImove\-link\-prev\fR)
.RE
.SS "EDIT KEYS"
.PP
\fIAlt\-"<"\fR
.RS 4
Go to the first line of the buffer (\fIbeginning\-of\-buffer\fR)
.RE
.PP
\fIAlt\-">"\fR
.RS 4
Go to the last line of the buffer (\fIend\-of\-buffer\fR)
.RE
.PP
\fICtrl\-"A"\fR
.RS 4
Go to the start of the page/line (\fIhome\fR)
.RE
.PP
\fIAlt\-"b"\fR
.RS 4
Move cursor before current word (\fImove\-backward\-word\fR)
.RE
.PP
\fICtrl\-"D"\fR
.RS 4
Delete character under cursor (\fIdelete\fR)
.RE
.PP
\fICtrl\-"E"\fR
.RS 4
Go to the end of the page/line (\fIend\fR)
.RE
.PP
\fIAlt\-"f"\fR
.RS 4
Move cursor after current word (\fImove\-forward\-word\fR)
.RE
.PP
\fICtrl\-"H"\fR
.RS 4
Delete character in front of the cursor (\fIbackspace\fR)
.RE
.PP
\fICtrl\-"K"\fR
.RS 4
Delete to end of line (\fIkill\-to\-eol\fR)
.RE
.PP
\fICtrl\-"L"\fR
.RS 4
Redraw the terminal (\fIredraw\fR)
.RE
.PP
\fIAlt\-"r"\fR
.RS 4
Toggle regex matching (type\-ahead searching) (\fIsearch\-toggle\-regex\fR)
.RE
.PP
\fICtrl\-"F"\fR
.RS 4
Attempt to auto\-complete a local file (\fIauto\-complete\-file\fR)
.RE
.PP
\fICtrl\-"R"\fR
.RS 4
Attempt to unambiguously auto\-complete the input (\fIauto\-complete\-unambiguous\fR)
.RE
.PP
\fICtrl\-"T"\fR
.RS 4
Open in external editor (\fIopen\-external\fR)
.RE
.PP
\fICtrl\-"U"\fR
.RS 4
Delete to beginning of line (\fIkill\-to\-bol\fR)
.RE
.PP
\fICtrl\-"V"\fR
.RS 4
Paste text from the clipboard (\fIpaste\-clipboard\fR)
.RE
.PP
\fICtrl\-"W"\fR
.RS 4
Attempt to auto\-complete the input (\fIauto\-complete\fR)
.RE
.PP
\fICtrl\-"X"\fR
.RS 4
Cut text to clipboard (\fIcut\-clipboard\fR)
.RE
.PP
\fIAlt\-Backspace\fR
.RS 4
Delete backwards to start of word (\fIkill\-word\-back\fR)
.RE
.PP
\fIBackspace\fR
.RS 4
Delete character in front of the cursor (\fIbackspace\fR)
.RE
.PP
\fIDelete\fR
.RS 4
Delete character under cursor (\fIdelete\fR)
.RE
.PP
\fIDown\fR
.RS 4
Move cursor downwards (\fIdown\fR)
.RE
.PP
\fIEnd\fR
.RS 4
Go to the end of the page/line (\fIend\fR)
.RE
.PP
\fIEnter\fR
.RS 4
Follow the current link (\fIenter\fR)
.RE
.PP
\fIEscape\fR
.RS 4
Cancel current state (\fIcancel\fR)
.RE
.PP
\fIF4\fR
.RS 4
Open in external editor (\fIopen\-external\fR)
.RE
.PP
\fIHome\fR
.RS 4
Go to the start of the page/line (\fIhome\fR)
.RE
.PP
\fICtrl\-Insert\fR
.RS 4
Copy text to clipboard (\fIcopy\-clipboard\fR)
.RE
.PP
\fILeft\fR
.RS 4
Move the cursor left (\fIleft\fR)
.RE
.PP
\fIRight\fR
.RS 4
Move the cursor right (\fIright\fR)
.RE
.PP
\fITab\fR
.RS 4
Move to the next item (\fInext\-item\fR)
.RE
.PP
\fIAlt\-Tab\fR
.RS 4
Move to the previous item (\fIprevious\-item\fR)
.RE
.PP
\fIShift\-Tab\fR
.RS 4
Move to the previous item (\fIprevious\-item\fR)
.RE
.PP
\fIUp\fR
.RS 4
Move cursor upwards (\fIup\fR)
.RE
.SS "MENU KEYS"
.PP
\fISpace\fR
.RS 4
Select current highlighted item (\fIselect\fR)
.RE
.PP
\fI"*"\fR
.RS 4
Mark item (\fImark\-item\fR)
.RE
.PP
\fI"+"\fR
.RS 4
Expand item (\fIexpand\fR)
.RE
.PP
\fI"\-"\fR
.RS 4
Collapse item (\fIunexpand\fR)
.RE
.PP
\fI"/"\fR
.RS 4
Search for a text pattern (\fIsearch\fR)
.RE
.PP
\fI"="\fR
.RS 4
Expand item (\fIexpand\fR)
.RE
.PP
\fICtrl\-"A"\fR
.RS 4
Go to the start of the page/line (\fIhome\fR)
.RE
.PP
\fICtrl\-"B"\fR
.RS 4
Move upwards by a page (\fIpage\-up\fR)
.RE
.PP
\fICtrl\-"E"\fR
.RS 4
Go to the end of the page/line (\fIend\fR)
.RE
.PP
\fICtrl\-"F"\fR
.RS 4
Move downwards by a page (\fIpage\-down\fR)
.RE
.PP
\fICtrl\-"L"\fR
.RS 4
Redraw the terminal (\fIredraw\fR)
.RE
.PP
\fICtrl\-"N"\fR
.RS 4
Move cursor downwards (\fIdown\fR)
.RE
.PP
\fICtrl\-"P"\fR
.RS 4
Move cursor upwards (\fIup\fR)
.RE
.PP
\fIAlt\-"V"\fR
.RS 4
Move upwards by a page (\fIpage\-up\fR)
.RE
.PP
\fICtrl\-"V"\fR
.RS 4
Move downwards by a page (\fIpage\-down\fR)
.RE
.PP
\fI"["\fR
.RS 4
Expand item (\fIexpand\fR)
.RE
.PP
\fI"]"\fR
.RS 4
Collapse item (\fIunexpand\fR)
.RE
.PP
\fI"_"\fR
.RS 4
Collapse item (\fIunexpand\fR)
.RE
.PP
\fIDelete\fR
.RS 4
Delete character under cursor (\fIdelete\fR)
.RE
.PP
\fIDown\fR
.RS 4
Move cursor downwards (\fIdown\fR)
.RE
.PP
\fIEnd\fR
.RS 4
Go to the end of the page/line (\fIend\fR)
.RE
.PP
\fIEnter\fR
.RS 4
Follow the current link (\fIenter\fR)
.RE
.PP
\fIEscape\fR
.RS 4
Cancel current state (\fIcancel\fR)
.RE
.PP
\fIHome\fR
.RS 4
Go to the start of the page/line (\fIhome\fR)
.RE
.PP
\fIInsert\fR
.RS 4
Mark item (\fImark\-item\fR)
.RE
.PP
\fILeft\fR
.RS 4
Move the cursor left (\fIleft\fR)
.RE
.PP
\fIPageDown\fR
.RS 4
Move downwards by a page (\fIpage\-down\fR)
.RE
.PP
\fIPageUp\fR
.RS 4
Move upwards by a page (\fIpage\-up\fR)
.RE
.PP
\fIRight\fR
.RS 4
Move the cursor right (\fIright\fR)
.RE
.PP
\fITab\fR
.RS 4
Move to the next item (\fInext\-item\fR)
.RE
.PP
\fIAlt\-Tab\fR
.RS 4
Move to the previous item (\fIprevious\-item\fR)
.RE
.PP
\fIShift\-Tab\fR
.RS 4
Move to the previous item (\fIprevious\-item\fR)
.RE
.PP
\fIUp\fR
.RS 4
Move cursor upwards (\fIup\fR)
.RE
.SH "AUTHOR"
.sp
This manual page was finally written by Peter Wang (one and a half years after writing the binding code), using excerpts by David Mediavilla\&. You can thank Petr Baudis for the subtle requests for documentation\&. Updated by Zas\&. Moved to asciidoc format and cleaned up by Jonas Fonseca\&.
.SH "SEE ALSO"
.sp
\fBelinks\fR(1), \fBelinks.conf\fR(5)
