path_to_top=../../..
include $(path_to_top)/Makefile.config

install-l:
	$(INSTALL_DATA) $(srcdir)/elinks.conf.5 $(DESTDIR)$(mandir)/man5
	$(INSTALL_DATA) $(srcdir)/elinkskeys.5 $(DESTDIR)$(mandir)/man5

include $(path_to_top)/Makefile.lib
