path_to_top=../../..
include $(path_to_top)/Makefile.config

install-local:
	$(INSTALL_DATA) elinks.conf.5 $(DESTDIR)$(mandir)/man5
	$(INSTALL_DATA) elinkskeys.5 $(DESTDIR)$(mandir)/man5

include $(path_to_top)/Makefile.lib
