top_builddir=../../..
include $(top_builddir)/Makefile.config

OBJS-$(CONFIG_MAILCAP)		+= mailcap.o
OBJS-$(CONFIG_MIMETYPES)	+= mimetypes.o

OBJS = common.o default.o

include $(top_srcdir)/Makefile.lib
