top_builddir=../../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(SPIDERMONKEY_CFLAGS)
SUBDIRS-$(CONFIG_SPIDERMONKEY) += spidermonkey
OBJS-$(CONFIG_SPIDERMONKEY) += spidermonkey.o

include $(top_srcdir)/Makefile.lib
