/* SpiderMonkey's DOM implementation */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "elinks.h"

#include "document/dom/ecmascript/spidermonkey.h"
#include "document/dom/ecmascript/spidermonkey/Attr.h"
#include "document/dom/ecmascript/spidermonkey/CDATASection.h"
#include "document/dom/ecmascript/spidermonkey/CharacterData.h"
#include "document/dom/ecmascript/spidermonkey/Comment.h"
#include "document/dom/ecmascript/spidermonkey/Document.h"
#include "document/dom/ecmascript/spidermonkey/DocumentFragment.h"
#include "document/dom/ecmascript/spidermonkey/DocumentType.h"
#include "document/dom/ecmascript/spidermonkey/DOMConfiguration.h"
#include "document/dom/ecmascript/spidermonkey/DOMError.h"
#include "document/dom/ecmascript/spidermonkey/DOMErrorHandler.h"
#include "document/dom/ecmascript/spidermonkey/DOMException.h"
#include "document/dom/ecmascript/spidermonkey/DOMImplementation.h"
#include "document/dom/ecmascript/spidermonkey/DOMImplementationList.h"
#include "document/dom/ecmascript/spidermonkey/DOMImplementationRegistry.h"
#include "document/dom/ecmascript/spidermonkey/DOMImplementationSource.h"
#include "document/dom/ecmascript/spidermonkey/DOMLocator.h"
#include "document/dom/ecmascript/spidermonkey/DOMStringList.h"
#include "document/dom/ecmascript/spidermonkey/Element.h"
#include "document/dom/ecmascript/spidermonkey/Entity.h"
#include "document/dom/ecmascript/spidermonkey/EntityReference.h"
#include "document/dom/ecmascript/spidermonkey/NamedNodeMap.h"
#include "document/dom/ecmascript/spidermonkey/NameList.h"
#include "document/dom/ecmascript/spidermonkey/Node.h"
#include "document/dom/ecmascript/spidermonkey/Notation.h"
#include "document/dom/ecmascript/spidermonkey/ProcessingInstruction.h"
#include "document/dom/ecmascript/spidermonkey/Text.h"
#include "document/dom/ecmascript/spidermonkey/TypeInfo.h"
#include "document/dom/ecmascript/spidermonkey/UserDataHandler.h"
