path_to_top=../../..
include $(path_to_top)/Makefile.config

install-local:
	$(MKINSTALLDIRS) $(DESTDIR)$(mandir)/man1
	$(INSTALL_DATA) elinks.1 $(DESTDIR)$(mandir)/man1

include $(path_to_top)/Makefile.lib
