path_to_top=../../..
include $(path_to_top)/Makefile.config

OBJS = navigator.o node.o renderer.o

# Do not forget to also add the .o to ../Makefile. Yes, it sucks.
all-l: $(OBJS)

include $(path_to_top)/Makefile.lib
