top_builddir=../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(TRE_CFLAGS)

OBJS-$(CONFIG_MARKS) += marks.o

OBJS = draw.o form.obj link.o search.o textarea.o view.o vs.o

include $(top_srcdir)/Makefile.lib
