top_builddir=../../..
include $(top_builddir)/Makefile.config

INCLUDES += $(TRE_CFLAGS)

OBJS-$(CONFIG_MARKS) += marks.o

OBJS = draw.o form.obj link.obj search.o textarea.o view.obj vs.obj

include $(top_srcdir)/Makefile.lib
