top_builddir=../../../..
include $(top_builddir)/Makefile.config

OBJS = attr.o attributes.o collection.o console.o forms.o history.o implementation.o keyboard.o localstorage.o mapa.obj message.o navigator.o nodelist.o

include $(top_srcdir)/Makefile.lib
